### ISSUE TITLE
Ark UI React: 2.0

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/ark#2051]
### Root Exports

To enhance RSC (React Server Components) and maintain overall consistency, export dedicated root components.

```ts
// Before
const Avatar = Object.assign(AvatarRoot, {
  Root: AvatarRoot,
  Fallback: AvatarFallback,
  Image: AvatarImage,
})

export { Avatar, AvatarFallback, AvatarImage, useAvatarContext }

// After
export const Avatar = {
  Root: AvatarRoot,
  Fallback: AvatarFallback,
  Image: AvatarImage,
}

export { AvatarFallback, AvatarImage, AvatarRoot, useAvatarContext }
```

A noticeable change is the type change for the root components:

```jsx
// Before
import type { AvatarProps } from '@ark-ui/react'

// After
import type { AvatarRootProps } from '@ark-ui/react'
```

For developers using dot notation, there is no significant change.

```jsx
// Before & After
import { Avatar } from '@ark-ui/react' // or '@ark-ui/react/avatar'

export const App = () => (
  <Avatar.Root>
    <Avatar.Fallback>PA</Avatar.Fallback>
    <Avatar.Image src="https://i.pravatar.cc/300" alt="avatar" />
  </Avatar.Root>
)
```

However, if you imported component parts individually, your codebase needs to be updated:

```jsx
// Before
import { Avatar, AvatarFallback, AvatarImage } from '@ark-ui/react'

export const App = () => (
  <Avatar>
    <AvatarFallback>PA</Avatar.Fallback>
    <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
  </Avatar>
)

// After
import { AvatarRoot, AvatarFallback, AvatarImage } from '@ark-ui/react'

export const App = () => (
  <AvatarRoot>
    <AvatarFallback>PA</Avatar.Fallback>
    <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
  </AvatarRoot>
)
```

### Provider Components

For provider components such as `Environment` and `Presence`, remove `.Root` to simplify the overall API.

```jsx
// Before
<Presence.Root>...</Presence.Root>

// After
<Presence>...</Presence>
```

Pull Request: [https://github.com/chakra-ui/ark/pull/1883](https://github.com/chakra-ui/ark/pull/1883)

### Todos

- [x] Integrate `TagsInput` changes -> waiting for Zag.js Release
- [x] Update Ark UI Website (using React)
- [x] Gather feedback from the community

**Comment by cschroeter** [comment]
Released.
