### ISSUE TITLE
Ark UI Solid: 2.0

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/ark#2052]
# Highlights

## Redesign of the `asChild` Prop

Both our team and contributors, as highlighted in [this issue](https://github.com/chakra-ui/ark/issues/2008), have encountered challenges when using the `asChild` prop within the Solid.js framework. The issues are significant enough to suggest that our initial approach may not be viable. Currently, we are evaluating several proposals, including [PR#2010](https://github.com/chakra-ui/ark/pull/2010) and [PR#2050](https://github.com/chakra-ui/ark/pull/2050), to find a suitable solution.

Our goal is to transition from the current syntax to a more streamlined approach, as illustrated below:

```jsx
// Current implementation
<Popover.Trigger asChild>
  <Button variant="primary">
    Open Popover
  </Button>
</Popover.Trigger>
```
```jsx
// Proposed implementation
<Popover.Trigger as={Button} variant="primary">
  Open Popover
</Popover.Trigger>
```
## Root Exports

To maintain overall consistency, export dedicated root components.

```ts
// Before
const Avatar = Object.assign(AvatarRoot, {
  Root: AvatarRoot,
  Fallback: AvatarFallback,
  Image: AvatarImage,
})

export { Avatar, AvatarFallback, AvatarImage, useAvatarContext }

// After
export const Avatar = {
  Root: AvatarRoot,
  Fallback: AvatarFallback,
  Image: AvatarImage,
}

export { AvatarFallback, AvatarImage, AvatarRoot, useAvatarContext }
```

A noticeable change is the type change for the root components:

```jsx
// Before
import type { AvatarProps } from '@ark-ui/solid'

// After
import type { AvatarRootProps } from '@ark-ui/solid'
```

For developers using dot notation, there is no significant change.

```jsx
// Before & After
import { Avatar } from '@ark-ui/solid'

export const App = () => (
  <Avatar.Root>
    <Avatar.Fallback>PA</Avatar.Fallback>
    <Avatar.Image src="https://i.pravatar.cc/300" alt="avatar" />
  </Avatar.Root>
)
```

However, if you imported component parts individually, your codebase needs to be updated:

```jsx
// Before
import { Avatar, AvatarFallback, AvatarImage } from '@ark-ui/solid'

export const App = () => (
  <Avatar>
    <AvatarFallback>PA</Avatar.Fallback>
    <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
  </Avatar>
)

// After
import { AvatarRoot, AvatarFallback, AvatarImage } from '@ark-ui/solid'

export const App = () => (
  <AvatarRoot>
    <AvatarFallback>PA</Avatar.Fallback>
    <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
  </AvatarRoot>
)
```

## Provider Components

For provider components such as `Environment` and `Presence`, remove `.Root` to simplify the overall API.

```jsx
// Before
<Presence.Root>...</Presence.Root>

// After
<Presence>...</Presence>
```

Pull Request: [https://github.com/chakra-ui/ark/pull/1883](https://github.com/chakra-ui/ark/pull/1883)

## Todos

- [x] Integrate `TagsInput` changes -> waiting for Zag.js Release
- [x] Type inference from `as` prop
- [x] Gather feedback from the community

**Comment by juliomuhlbauer** [comment]
The as prop is much better in my opinion compared to asChild. It would be amazing to see Ark and Panda returning to as prop.

For semantic reasons, I much prefer putting an as prop like "section", instead of putting asChild and putting an section inside the element.

**Comment by cschroeter** [comment]
Released.
